// ==========================================
// RANKDLE
//
// Two people on screen at a time. Pick the
// better one, the loser gets swapped out for
// a new face, and nobody shows up twice in
// the same session.
//
// Requires people.js (generated by tools/build.mjs)
// to be loaded first.
// ==========================================


// ------------------------------------------
// CONFIG
// ------------------------------------------

const STORAGE_PREFIX = "rankdle:v1:";

// Timing of a pick: both cards hold still long enough to read the
// community scores (HOLD), the loser then fades out (FADE) and the
// replacement slides into the empty slot.
const HOLD_DELAY = 600;
const FADE_DELAY = 460;


// ------------------------------------------
// STATE
// ------------------------------------------

const state = {
    key: dayKey(new Date()),
    slots: [null, null],   // the two people on screen, left and right
    seen: new Set(),       // names already shown this session
    queue: [],             // shuffled roster positions still waiting
    rounds: 0,             // picks made
    agree: 0,              // picks that matched the community score
    enterIndex: null,      // card to animate in on the next render
    busy: false            // a swap is animating
};


// ------------------------------------------
// DAILY KEY (session id, so stats survive a refresh)
// ------------------------------------------

function dayKey(date) {
    const year = date.getFullYear();
    const month = String(date.getMonth() + 1).padStart(2, "0");
    const day = String(date.getDate()).padStart(2, "0");

    return `${year}-${month}-${day}`;
}


function shuffle(list, random = Math.random) {
    for (let i = list.length - 1; i > 0; i--) {

        const j = Math.floor(random() * (i + 1));

        [list[i], list[j]] = [list[j], list[i]];
    }

    return list;
}


// ------------------------------------------
// PICKING PEOPLE
//
// Every person shown gets added to `seen`, so
// the next replacement is always somebody new.
// ------------------------------------------

function fillQueue() {
    state.queue = shuffle(ROSTER.map((person, index) => index));
}


function takeFromQueue(excluded) {

    while (state.queue.length) {

        const person = ROSTER[state.queue.pop()];

        if (!person || state.seen.has(person.name) || excluded.has(person.name)) {
            continue;
        }

        state.seen.add(person.name);

        return person;
    }

    return null;
}


// A new, never-shown-this-session person who is
// not one of the names in `excluded`.
function nextPerson(excluded) {

    const found = takeFromQueue(excluded);

    if (found) {
        return found;
    }

    // Whole roster has been used up - start over, but keep
    // whoever is currently on screen out of the fresh pool.
    state.seen = new Set(excluded);
    fillQueue();

    return takeFromQueue(excluded);
}


function freshPair() {

    fillQueue();

    const left = nextPerson(new Set());
    const right = nextPerson(new Set([left.name]));

    return [left, right];
}


// ------------------------------------------
// STORAGE
// ------------------------------------------

function loadStats() {
    try {
        const raw = localStorage.getItem(STORAGE_PREFIX + state.key);

        return raw ? JSON.parse(raw) : null;
    } catch (error) {
        return null;
    }
}


function saveStats() {
    try {
        localStorage.setItem(STORAGE_PREFIX + state.key, JSON.stringify({
            rounds: state.rounds,
            agree: state.agree,
            seen: [...state.seen],
            slots: state.slots.filter(Boolean).map((person) => person.name)
        }));
    } catch (error) {
        // Private browsing - the game still works, it just forgets.
    }
}


// ?reset=1 wipes the session so you can play again while testing.
function handleReset() {
    const params = new URLSearchParams(window.location.search);

    if (!params.has("reset")) {
        return;
    }

    localStorage.removeItem(STORAGE_PREFIX + state.key);

    params.delete("reset");

    const query = params.toString();

    history.replaceState(
        {},
        "",
        window.location.pathname + (query ? `?${query}` : "")
    );
}


// ------------------------------------------
// HELPERS
// ------------------------------------------

function initialsFor(name) {
    const ignored = new Set(["the", "a", "an", "of", "and"]);

    const words = name
        .split(/\s+/)
        .filter((word) => word.length > 1 && !ignored.has(word.toLowerCase()));

    const source = words.length ? words : name.split(/\s+/);

    if (source.length === 1) {
        return source[0].slice(0, 2).toUpperCase();
    }

    return (source[0][0] + source[1][0]).toUpperCase();
}


function byName(name) {
    return ROSTER.find((person) => person.name === name) || null;
}


// The build writes a unique rank (1..N) as `score` - there are far more
// people than 100 now, so a 0-99 scale would create ties. Cards show it
// as a 0-100 "community score" instead.
const SCORE_MAX =
    typeof ROSTER !== "undefined" && Array.isArray(ROSTER) && ROSTER.length
        ? Math.max(...ROSTER.map((person) => person.score))
        : 100;


function scoreFor(person) {
    if (!person || !person.score) {
        return 0;
    }

    return Math.max(1, Math.min(100, Math.round((person.score / SCORE_MAX) * 100)));
}


function formatDate(date) {
    return new Intl.DateTimeFormat("en-US", {
        month: "long",
        day: "numeric",
        year: "numeric"
    }).format(date);
}


// ------------------------------------------
// RENDERING
// ------------------------------------------

const container = document.getElementById("people-container");
const statRounds = document.getElementById("stat-rounds");
const statAgree = document.getElementById("stat-agree");
const statLeft = document.getElementById("stat-left");
const statusLine = document.getElementById("duel-status");
const rosterCount = document.getElementById("roster-count");


function cardMarkup(person) {
    const photo = person.image
        ? `<img src="${person.image}" alt="" loading="lazy">`
        : "";

    const tag = person.tag
        ? `<span class="person-tag">${person.tag}</span>`
        : "";

    return `
        <div class="portrait">
            <span class="initials" aria-hidden="true">${initialsFor(person.name)}</span>
            ${photo}
            ${tag}
            <span class="score-chip" aria-hidden="true">
                <span class="score-chip-label">COMMUNITY</span>
                <span class="score-chip-value">${scoreFor(person)}</span>
            </span>
            <span class="pick-hint" aria-hidden="true">PICK</span>
        </div>
        <span class="person-name">${person.name}</span>
        <span class="person-years">${person.years}</span>
        <span class="person-role">${person.role}</span>
    `;
}


function buildCard(person, index) {

    const card = document.createElement("div");

    card.className = "person-card";
    card.tabIndex = 0;
    card.setAttribute("role", "button");
    card.dataset.name = person.name;
    card.dataset.index = String(index);
    card.dataset.tag = person.tag || "";
    card.innerHTML = cardMarkup(person);

    if (state.enterIndex === index) {
        card.classList.add("enter");
    }

    const image = card.querySelector("img");

    if (image) {
        image.addEventListener("error", () => {
            card.classList.add("no-photo");
        });
    }

    card.setAttribute(
        "aria-label",
        `Pick ${person.name} as the better person. ${person.role}, ${person.years}.`
    );

    return card;
}


function render() {

    container.innerHTML = "";

    state.slots.forEach((person, index) => {
        if (person) {
            container.appendChild(buildCard(person, index));
        }
    });

    state.enterIndex = null;
}


function updateStats() {

    statRounds.textContent = String(state.rounds);

    statAgree.textContent = state.rounds
        ? `${Math.round((state.agree / state.rounds) * 100)}%`
        : "\u2014";

    if (statLeft) {
        statLeft.textContent = String(
            Math.max(0, ROSTER.length - state.seen.size)
        );
    }
}


// ------------------------------------------
// PICKING
// ------------------------------------------

function pick(index) {

    if (state.busy || !state.slots[index]) {
        return;
    }

    const other = 1 - index;
    const winner = state.slots[index];
    const loser = state.slots[other];

    state.busy = true;
    state.rounds++;

    // The community ranking is the `score` on each person:
    // higher = better, so that is who the site says is right.
    const agreed = winner.score > loser.score;

    if (agreed) {
        state.agree++;
    }

    // Work out the replacement straight away so it is ready
    // the moment the animation lands. This also grows `seen`.
    const replacement = nextPerson(new Set([winner.name, loser.name]));

    updateStats();
    showStatus(agreed, winner, loser);

    const cards = [...container.children];

    // Both cards show their community score first...
    if (cards[index]) cards[index].classList.add("chosen", "revealed");
    if (cards[other]) cards[other].classList.add("revealed");

    // ...then the loser fades, then the replacement slides in.
    window.setTimeout(() => {

        if (cards[other]) cards[other].classList.add("replaced");

        window.setTimeout(() => {

            state.slots[other] = replacement;
            state.enterIndex = other;

            hideStatus();
            saveStats();
            render();

            state.busy = false;

        }, FADE_DELAY);

    }, HOLD_DELAY);
}


function showStatus(agreed, winner, loser) {

    if (!statusLine) {
        return;
    }

    const pickText = `${winner.name} ${scoreFor(winner)}`;
    const otherText = `${loser.name} ${scoreFor(loser)}`;

    statusLine.className = `duel-status ${agreed ? "is-agree" : "is-disagree"}`;
    statusLine.textContent = agreed
        ? `\u2713 You agreed with the community \u2014 ${pickText} beats ${otherText}`
        : `\u2715 You disagreed \u2014 the community prefers ${otherText} over ${pickText}`;
}


function hideStatus() {

    if (!statusLine) {
        return;
    }

    statusLine.className = "duel-status";
    statusLine.textContent = "";
}


container.addEventListener("click", (event) => {

    const card = event.target.closest(".person-card");

    if (!card) {
        return;
    }

    pick(Number(card.dataset.index));
});


container.addEventListener("keydown", (event) => {

    if (event.key !== "Enter" && event.key !== " ") {
        return;
    }

    const card = event.target.closest(".person-card");

    if (!card) {
        return;
    }

    event.preventDefault();

    pick(Number(card.dataset.index));
});


// ------------------------------------------
// START
// ------------------------------------------

handleReset();

document.getElementById("today-date").textContent =
    formatDate(new Date()).toUpperCase();

if (rosterCount && typeof ROSTER !== "undefined" && Array.isArray(ROSTER)) {
    rosterCount.textContent = String(ROSTER.length);
}

if (!Array.isArray(ROSTER) || ROSTER.length < 3) {

    container.innerHTML =
        "<p class='hint'>No people loaded. Run <code>node tools/build.mjs</code> first.</p>";

} else {

    const saved = loadStats();

    // The queue of "who is left to show" starts empty every load -
    // refill it, then let `seen` do the filtering.
    fillQueue();

    if (saved) {

        state.rounds = Number(saved.rounds) || 0;
        state.agree = Number(saved.agree) || 0;

        if (Array.isArray(saved.seen)) {
            saved.seen.forEach((name) => {
                if (byName(name)) {
                    state.seen.add(name);
                }
            });
        }

        if (
            Array.isArray(saved.slots) &&
            saved.slots.length === 2 &&
            saved.slots[0] !== saved.slots[1] &&
            saved.slots.every((name) => byName(name))
        ) {
            state.slots = saved.slots.map(byName);
        }
    }

    if (!state.slots[0] || !state.slots[1]) {
        state.slots = freshPair();
    }

    state.slots.forEach((person) => state.seen.add(person.name));

    updateStats();
    render();
}
