// ==========================================
// RANKDLE
//
// Two people on screen at a time. Pick the
// better one, the loser gets swapped out for
// a new face, and nobody shows up twice in
// the same session.
//
// Requires people.js (generated by tools/build.mjs)
// to be loaded first.
// ==========================================


// ------------------------------------------
// CONFIG
// ------------------------------------------

const STORAGE_PREFIX = "rankdle:v1:";

// How long the winner / loser flash lasts before
// the loser's card is replaced.
const SWAP_DELAY = 340;


// ------------------------------------------
// STATE
// ------------------------------------------

const state = {
    key: dayKey(new Date()),
    slots: [null, null],   // the two people on screen, left and right
    seen: new Set(),       // names already shown this session
    queue: [],             // shuffled roster positions still waiting
    rounds: 0,             // picks made
    agree: 0,              // picks that matched the community score
    enterIndex: null,      // card to animate in on the next render
    busy: false            // a swap is animating
};


// ------------------------------------------
// DAILY KEY (session id, so stats survive a refresh)
// ------------------------------------------

function dayKey(date) {
    const year = date.getFullYear();
    const month = String(date.getMonth() + 1).padStart(2, "0");
    const day = String(date.getDate()).padStart(2, "0");

    return `${year}-${month}-${day}`;
}


function shuffle(list, random = Math.random) {
    for (let i = list.length - 1; i > 0; i--) {

        const j = Math.floor(random() * (i + 1));

        [list[i], list[j]] = [list[j], list[i]];
    }

    return list;
}


// ------------------------------------------
// PICKING PEOPLE
//
// Every person shown gets added to `seen`, so
// the next replacement is always somebody new.
// ------------------------------------------

function fillQueue() {
    state.queue = shuffle(ROSTER.map((person, index) => index));
}


function takeFromQueue(excluded) {

    while (state.queue.length) {

        const person = ROSTER[state.queue.pop()];

        if (!person || state.seen.has(person.name) || excluded.has(person.name)) {
            continue;
        }

        state.seen.add(person.name);

        return person;
    }

    return null;
}


// A new, never-shown-this-session person who is
// not one of the names in `excluded`.
function nextPerson(excluded) {

    const found = takeFromQueue(excluded);

    if (found) {
        return found;
    }

    // Whole roster has been used up - start over, but keep
    // whoever is currently on screen out of the fresh pool.
    state.seen = new Set(excluded);
    fillQueue();

    return takeFromQueue(excluded);
}


function freshPair() {

    fillQueue();

    const left = nextPerson(new Set());
    const right = nextPerson(new Set([left.name]));

    return [left, right];
}


// ------------------------------------------
// STORAGE
// ------------------------------------------

function loadStats() {
    try {
        const raw = localStorage.getItem(STORAGE_PREFIX + state.key);

        return raw ? JSON.parse(raw) : null;
    } catch (error) {
        return null;
    }
}


function saveStats() {
    try {
        localStorage.setItem(STORAGE_PREFIX + state.key, JSON.stringify({
            rounds: state.rounds,
            agree: state.agree,
            seen: [...state.seen],
            slots: state.slots.filter(Boolean).map((person) => person.name)
        }));
    } catch (error) {
        // Private browsing - the game still works, it just forgets.
    }
}


// ?reset=1 wipes the session so you can play again while testing.
function handleReset() {
    const params = new URLSearchParams(window.location.search);

    if (!params.has("reset")) {
        return;
    }

    localStorage.removeItem(STORAGE_PREFIX + state.key);

    params.delete("reset");

    const query = params.toString();

    history.replaceState(
        {},
        "",
        window.location.pathname + (query ? `?${query}` : "")
    );
}


// ------------------------------------------
// HELPERS
// ------------------------------------------

function initialsFor(name) {
    const ignored = new Set(["the", "a", "an", "of", "and"]);

    const words = name
        .split(/\s+/)
        .filter((word) => word.length > 1 && !ignored.has(word.toLowerCase()));

    const source = words.length ? words : name.split(/\s+/);

    if (source.length === 1) {
        return source[0].slice(0, 2).toUpperCase();
    }

    return (source[0][0] + source[1][0]).toUpperCase();
}


function byName(name) {
    return ROSTER.find((person) => person.name === name) || null;
}


function formatDate(date) {
    return new Intl.DateTimeFormat("en-US", {
        month: "long",
        day: "numeric",
        year: "numeric"
    }).format(date);
}


// ------------------------------------------
// RENDERING
// ------------------------------------------

const container = document.getElementById("people-container");
const statRounds = document.getElementById("stat-rounds");
const statAgree = document.getElementById("stat-agree");


function cardMarkup(person) {
    const photo = person.image
        ? `<img src="${person.image}" alt="" loading="lazy">`
        : "";

    return `
        <div class="portrait">
            <span class="initials" aria-hidden="true">${initialsFor(person.name)}</span>
            ${photo}
            <span class="pick-hint" aria-hidden="true">PICK</span>
        </div>
        <span class="person-name">${person.name}</span>
        <span class="person-years">${person.years}</span>
        <span class="person-role">${person.role}</span>
    `;
}


function buildCard(person, index) {

    const card = document.createElement("div");

    card.className = "person-card";
    card.tabIndex = 0;
    card.setAttribute("role", "button");
    card.dataset.name = person.name;
    card.dataset.index = String(index);
    card.innerHTML = cardMarkup(person);

    if (state.enterIndex === index) {
        card.classList.add("enter");
    }

    const image = card.querySelector("img");

    if (image) {
        image.addEventListener("error", () => {
            card.classList.add("no-photo");
        });
    }

    card.setAttribute(
        "aria-label",
        `Pick ${person.name} as the better person. ${person.role}, ${person.years}.`
    );

    return card;
}


function render() {

    container.innerHTML = "";

    state.slots.forEach((person, index) => {
        if (person) {
            container.appendChild(buildCard(person, index));
        }
    });

    state.enterIndex = null;
}


function updateStats() {

    statRounds.textContent = String(state.rounds);

    statAgree.textContent = state.rounds
        ? `${Math.round((state.agree / state.rounds) * 100)}%`
        : "\u2014";
}


// ------------------------------------------
// PICKING
// ------------------------------------------

function pick(index) {

    if (state.busy || !state.slots[index]) {
        return;
    }

    const other = 1 - index;
    const winner = state.slots[index];
    const loser = state.slots[other];

    state.busy = true;
    state.rounds++;

    // The community ranking is the `score` on each person:
    // higher = better, so that is who the site says is right.
    if (winner.score > loser.score) {
        state.agree++;
    }

    updateStats();

    const cards = [...container.children];

    if (cards[index]) cards[index].classList.add("chosen");
    if (cards[other]) cards[other].classList.add("replaced");

    // Work out the replacement straight away so it is ready
    // the moment the animation lands.
    const replacement = nextPerson(new Set([winner.name, loser.name]));

    window.setTimeout(() => {

        state.slots[other] = replacement;
        state.enterIndex = other;

        saveStats();
        render();

        state.busy = false;

    }, SWAP_DELAY);
}


container.addEventListener("click", (event) => {

    const card = event.target.closest(".person-card");

    if (!card) {
        return;
    }

    pick(Number(card.dataset.index));
});


container.addEventListener("keydown", (event) => {

    if (event.key !== "Enter" && event.key !== " ") {
        return;
    }

    const card = event.target.closest(".person-card");

    if (!card) {
        return;
    }

    event.preventDefault();

    pick(Number(card.dataset.index));
});


// ------------------------------------------
// START
// ------------------------------------------

handleReset();

document.getElementById("today-date").textContent =
    formatDate(new Date()).toUpperCase();

if (!Array.isArray(ROSTER) || ROSTER.length < 3) {

    container.innerHTML =
        "<p class='hint'>No people loaded. Run <code>node tools/build.mjs</code> first.</p>";

} else {

    const saved = loadStats();

    // The queue of "who is left to show" starts empty every load -
    // refill it, then let `seen` do the filtering.
    fillQueue();

    if (saved) {

        state.rounds = Number(saved.rounds) || 0;
        state.agree = Number(saved.agree) || 0;

        if (Array.isArray(saved.seen)) {
            saved.seen.forEach((name) => {
                if (byName(name)) {
                    state.seen.add(name);
                }
            });
        }

        if (
            Array.isArray(saved.slots) &&
            saved.slots.length === 2 &&
            saved.slots[0] !== saved.slots[1] &&
            saved.slots.every((name) => byName(name))
        ) {
            state.slots = saved.slots.map(byName);
        }
    }

    if (!state.slots[0] || !state.slots[1]) {
        state.slots = freshPair();
    }

    state.slots.forEach((person) => state.seen.add(person.name));

    updateStats();
    render();
}
