// ==========================================
// RANKDLE
//
// Two people on screen at a time. Pick the
// better one, the loser gets swapped out for
// a new face, and nobody shows up twice in
// the same session.
//
// Requires people.js (generated by tools/build.mjs)
// to be loaded first.
// ==========================================


// ------------------------------------------
// CONFIG
// ------------------------------------------

const STORAGE_PREFIX = "rankdle:v1:";

// Timing of a pick: the chosen card holds just long enough to read as
// a pick (HOLD), the other then fades out (FADE) and the replacement
// slides into the empty slot.
const HOLD_DELAY = 240;
const FADE_DELAY = 400;


// ------------------------------------------
// DATA
//
// people.js gives the roster; ratings.js (generated from
// ratings.json) gives the six game ratings keyed by name.
// Merge them once here so every part of the game can score
// people directly. Anyone without ratings gets neutral ones.
// ------------------------------------------

const RATINGS_TABLE = typeof RATINGS !== "undefined" ? RATINGS : {};

const NEUTRAL_RATINGS = { fame: 3, era: 3, morality: 3, controversy: 3, gender: 0, fiction: 0 };

const PEOPLE = (typeof ROSTER !== "undefined" ? ROSTER : []).map((person) => ({
    ...person,
    ...NEUTRAL_RATINGS,
    ...(RATINGS_TABLE[person.name] || {})
}));


// ------------------------------------------
// STATE
// ------------------------------------------

const state = {
    key: dayKey(new Date()),
    slots: [null, null],   // the two people on screen, left and right
    seen: new Set(),       // names already shown this session
    enterIndex: null,      // card to animate in on the next render
    initial: true,         // the very first paint, where both cards rise in
    busy: false            // a swap is animating
};


// ------------------------------------------
// DAILY KEY (session id, so the session survives a refresh)
// ------------------------------------------

function dayKey(date) {
    const year = date.getFullYear();
    const month = String(date.getMonth() + 1).padStart(2, "0");
    const day = String(date.getDate()).padStart(2, "0");

    return `${year}-${month}-${day}`;
}


// ------------------------------------------
// PICKING PEOPLE (stat-driven)
//
// Nobody shows up twice in a session, and the next card is
// not a random draw: it is whoever is MOST DIFFERENT from
// the card that stays on screen, measured across the six
// ratings in ratings.json. Exact ties are broken at random.
// ------------------------------------------

// How different two people are, 0-30. Every stat is normalised
// to 0-1 first (so all six weigh equally) then scored in integer
// fifths: the four 0-5 stats contribute up to 5 each, gender and
// fiction up to 5 each. Integers keep tie comparisons exact.
function differenceScore(a, b) {
    return (
        Math.abs(a.fame - b.fame) +
        Math.abs(a.era - b.era) +
        Math.abs(a.morality - b.morality) +
        Math.abs(a.controversy - b.controversy) +
        5 * Math.abs(a.gender - b.gender) +
        5 * Math.abs(a.fiction - b.fiction)
    );
}


// The most different person in `pool` compared to `reference`.
// No reference (the very first card of a session) = random.
// People who are equally the most different = random among them.
function mostDifferent(pool, reference) {

    if (!pool.length) {
        return null;
    }

    if (!reference) {
        return pool[Math.floor(Math.random() * pool.length)];
    }

    let best = [];
    let bestScore = -1;

    for (const person of pool) {

        const score = differenceScore(person, reference);

        if (score > bestScore) {
            bestScore = score;
            best = [person];
        } else if (score === bestScore) {
            best.push(person);
        }
    }

    return best[Math.floor(Math.random() * best.length)];
}


// Everybody not yet shown this session and not in `excluded`.
function eligiblePool(excluded) {
    return PEOPLE.filter(
        (person) => !state.seen.has(person.name) && !excluded.has(person.name)
    );
}


// A new, never-shown-this-session person who is maximally
// different from `reference` and not one of `excluded`.
function nextPerson(excluded, reference) {

    let found = mostDifferent(eligiblePool(excluded), reference);

    if (found) {
        state.seen.add(found.name);
        return found;
    }

    // Whole roster has been used up - start over, but keep
    // whoever is currently on screen out of the fresh pool.
    state.seen = new Set(excluded);

    found = mostDifferent(eligiblePool(excluded), reference);

    if (found) {
        state.seen.add(found.name);
    }

    return found;
}


function freshPair() {

    // Nothing to be different from yet, so the first card is
    // random - then the second is its polar opposite.
    const left = nextPerson(new Set(), null);
    const right = nextPerson(new Set([left.name]), left);

    return [left, right];
}


// ------------------------------------------
// STORAGE
// ------------------------------------------

function loadSession() {
    try {
        const raw = localStorage.getItem(STORAGE_PREFIX + state.key);

        return raw ? JSON.parse(raw) : null;
    } catch (error) {
        return null;
    }
}


function saveSession() {
    try {
        localStorage.setItem(STORAGE_PREFIX + state.key, JSON.stringify({
            seen: [...state.seen],
            slots: state.slots.filter(Boolean).map((person) => person.name)
        }));
    } catch (error) {
        // Private browsing - the game still works, it just forgets.
    }
}


// ?reset=1 wipes the session so you can play again while testing.
function handleReset() {
    const params = new URLSearchParams(window.location.search);

    if (!params.has("reset")) {
        return;
    }

    localStorage.removeItem(STORAGE_PREFIX + state.key);

    params.delete("reset");

    const query = params.toString();

    history.replaceState(
        {},
        "",
        window.location.pathname + (query ? `?${query}` : "")
    );
}


// ------------------------------------------
// HELPERS
// ------------------------------------------

function initialsFor(name) {
    const ignored = new Set(["the", "a", "an", "of", "and"]);

    const words = name
        .split(/\s+/)
        .filter((word) => word.length > 1 && !ignored.has(word.toLowerCase()));

    const source = words.length ? words : name.split(/\s+/);

    if (source.length === 1) {
        return source[0].slice(0, 2).toUpperCase();
    }

    return (source[0][0] + source[1][0]).toUpperCase();
}


function byName(name) {
    return PEOPLE.find((person) => person.name === name) || null;
}


function formatDate(date) {
    return new Intl.DateTimeFormat("en-US", {
        month: "long",
        day: "numeric",
        year: "numeric"
    }).format(date);
}


// ------------------------------------------
// RENDERING
// ------------------------------------------

const container = document.getElementById("people-container");


function cardMarkup(person) {
    const photo = person.image
        ? `<img src="${person.image}" alt="" loading="lazy">`
        : "";

    const tag = person.tag
        ? `<span class="person-tag">${person.tag}</span>`
        : "";

    return `
        <div class="portrait">
            <span class="initials" aria-hidden="true">${initialsFor(person.name)}</span>
            ${photo}
            ${tag}
        </div>
        <div class="person-info">
            <div class="person-text">
                <span class="person-name">${person.name}</span>
                <span class="person-meta">
                    <span class="person-years">${person.years}</span>
                    <span class="person-role">${person.role}</span>
                </span>
            </div>
            <span class="pick-btn" aria-hidden="true">
                <svg class="pick-arrow" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.2" stroke-linecap="round" stroke-linejoin="round"><path d="M4 12h14"/><path d="M12.5 5.5 19 12l-6.5 6.5"/></svg>
                <svg class="pick-check" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.4" stroke-linecap="round" stroke-linejoin="round"><path d="M5 12.5 10 17.5 19 7"/></svg>
            </span>
        </div>
    `;
}


function buildCard(person, index) {

    const card = document.createElement("div");

    card.className = "person-card";
    card.setAttribute("role", "button");
    card.dataset.name = person.name;
    card.dataset.index = String(index);
    card.dataset.tag = person.tag || "";
    card.innerHTML = cardMarkup(person);

    if (state.enterIndex === index) {
        card.classList.add("enter");
    }

    const image = card.querySelector("img");

    if (image) {
        image.addEventListener("error", () => {
            card.classList.add("no-photo");
        });
    }

    card.setAttribute(
        "aria-label",
        `Pick ${person.name} as the better person. ${person.role}, ${person.years}.`
    );

    return card;
}


function render() {

    container.innerHTML = "";

    state.slots.forEach((person, index) => {

        if (!person) {
            return;
        }

        const card = buildCard(person, index);

        // On the first paint both cards rise in, staggered.
        if (state.initial) {
            card.classList.add("enter");
            card.style.animationDelay = `${index * 0.08}s`;
        }

        container.appendChild(card);
    });

    state.enterIndex = null;
    state.initial = false;
}


// ------------------------------------------
// PICKING
// ------------------------------------------

function pick(index) {

    if (state.busy || !state.slots[index]) {
        return;
    }

    const other = 1 - index;
    const kept = state.slots[index];
    const replaced = state.slots[other];

    state.busy = true;

    // Work out the replacement straight away so it is ready
    // the moment the animation lands. This also grows `seen`.
    // It is the most different person from the one being kept.
    const replacement = nextPerson(new Set([kept.name, replaced.name]), kept);

    const cards = [...container.children];

    // The pick lights up for a beat...
    if (cards[index]) cards[index].classList.add("chosen");

    // ...then the other card fades and the replacement takes its place.
    window.setTimeout(() => {

        if (cards[other]) cards[other].classList.add("replaced");

        window.setTimeout(() => {

            state.slots[other] = replacement;
            state.enterIndex = other;

            saveSession();
            render();

            state.busy = false;

        }, FADE_DELAY);

    }, HOLD_DELAY);
}


container.addEventListener("click", (event) => {

    const card = event.target.closest(".person-card");

    if (!card) {
        return;
    }

    pick(Number(card.dataset.index));
});


// The card lights up under the cursor rather than glowing at random.
container.addEventListener("pointermove", (event) => {

    const card = event.target.closest(".person-card");

    if (!card) {
        return;
    }

    const box = card.getBoundingClientRect();

    card.style.setProperty("--mx", `${event.clientX - box.left}px`);
    card.style.setProperty("--my", `${event.clientY - box.top}px`);
});


// ------------------------------------------
// START
// ------------------------------------------

handleReset();

document.getElementById("today-date").textContent =
    formatDate(new Date()).toUpperCase();

if (!Array.isArray(PEOPLE) || PEOPLE.length < 3) {

    container.innerHTML =
        "<p class='hint'>No people loaded. Run <code>node tools/build.mjs</code> first.</p>";

} else {

    const saved = loadSession();

    if (saved) {

        if (Array.isArray(saved.seen)) {
            saved.seen.forEach((name) => {
                if (byName(name)) {
                    state.seen.add(name);
                }
            });
        }

        if (
            Array.isArray(saved.slots) &&
            saved.slots.length === 2 &&
            saved.slots[0] !== saved.slots[1] &&
            saved.slots.every((name) => byName(name))
        ) {
            state.slots = saved.slots.map(byName);
        }
    }

    if (!state.slots[0] || !state.slots[1]) {
        state.slots = freshPair();
    }

    state.slots.forEach((person) => state.seen.add(person.name));

    render();
}
